# Generated by Django 2.1 on 2020-02-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies_poster',
            name='video',
            field=models.FileField(default='', upload_to='videos/'),
        ),
    ]
